language: php

php:
  - 7.0
  - 7.1

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)